# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: "<%= ENV.fetch("DB_USERNAME") { "root" } %>"
  password: "<%= ENV.fetch("DB_PASSWORD") { "password" } %>"
  port: "<%= ENV.fetch("DB_PORT") { 3306 } %>"
  host: "<%= ENV.fetch("DB_HOST") { "localhost" } %>"
  database: "<%= ENV.fetch("DB_NAME") { "cashback_icms" } %>"
  socket: /var/run/mysqld/mysqlx.sock

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { "cashback_icms" } %>_dev

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { "cashback_icms" } %>_test

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { "cashback_icms" } %>_prod
